### ISSUE TITLE
Titan Addon

### ISSUE THREAD

**Issue by sliceu** [Icehunter/ffxivapp-plugin-informer#2]
I see that the warnings work on titan regular but not on extreme. Any idea how to get it to work?

**Comment by Icehunter** [comment]
This plugin doesn't have warnings and is a very basic concept one with plans to change it/depreciate it. What plugin are you referring too that offers warnings?

**Comment by sliceu** [comment]
Sorry i dint notice that you replied. i thought that this addon was part of the DBM mod and i saw it only worked on titan normal but not extreme

**Comment by Icehunter** [comment]
No worries!
